 
name: srnchairs_${dataset.resolution}
sampling:
  fov: 52.0
  ray_start: 0.6
  ray_end: 1.4  
  dist: spherical_uniform
  radius: 1.0
  horizontal_stddev: 3.141592653589793
  vertical_stddev: 0.785398163
  horizontal_mean: 1.57079632679
  vertical_mean: 0.785398163
cube_scale: 0.81
white_back: true
last_back: false
# c_dim: 513
