 

# Checkpoint loading options
ckpt:
  network_pkl: ~ # Network pickle filename
  networks_dir: ~ # Network pickles directory
  selection_metric: fid2k_full # Which metric to use when selecting the best ckpt?
  reload_code: false # If we changed the code and what to run with the new code, we can reload it.

# Main options
seeds: [11,12,13]
cube_size: 0.6
voxel_res: 16
max_batch_res: 2
voxel_origin: [0.0, 0.0, 0.0]
output_dir: shapes
thresh_percentile: 97.5

# Inference options
truncation_psi: 1.0 # 0.7 # Truncation psi.

# Logging options
verbose: true

